import "./globals.css";
import Menu from "./menu";
import SupabaseProvider from "./supabase-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <main className="min-h-full bg-gradient-to-bl from-indigo-950 to-slate-800">
            <div className="sticky top-0 z-10 w-full p-4 bg-slate-900 bg-opacity-50 backdrop-blur-lg">
              <div className="max-w-4xl w-full px-2 m-auto flex justify-between items-center">
                <h1 className="text-4xl font-bold bg-gradient-to-r from-cyan-400 to-violet-400 inline-block text-transparent bg-clip-text">
                  GuessAI
                </h1>
                <div className="">
                  <Menu />
                </div>
              </div>
            </div>
            {children}
          </main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
