import "./globals.css";
import SupabaseProvider from "./supabase-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <main className="h-full flex flex-col items-center justify-center bg-gradient-to-bl from-indigo-950 to-slate-800">
            {children}
          </main>
        </SupabaseProvider>
      </body>
    </html>
  );
}
